spring.application.name=news-service

spring.datasource.url=jdbc:postgresql://localhost:5432/news_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

server.port=8080

spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin
